### ISSUE TITLE
Задачи из чата 2

### ISSUE THREAD

**Issue by grigoriev-semyon** [profcomff/preparation-timetable-data#33]
- [ ]  Сделать загрузку через sqlalchemy. 

- [ ]  Логгирование, документация, качество кода.

**Comment by dyakovri** [comment]
preparation-timetable-data будет загружать ивенты через sqlalchemy? А как решили проблему автоматических индексов?

**Comment by grigoriev-semyon** [comment]
@dyakovri он же next создает

**Comment by grigoriev-semyon** [comment]
Загрузку через алхимию лучше не делать или делать только геты

**Comment by dyakovri** [comment]
Геты тоже лучше не делать)
