### ISSUE TITLE
Автоматический парсинг расписания при из его менениях

### ISSUE THREAD

**Issue by MarkShidran** [profcomff/preparation-timetable-data#36]
Зависит от:

- [x] #43 
- [x] #42 
- [x] #37 
- [x] #47

**Comment by grigoriev-semyon** [comment]
библиотека сделана? @SergeyZamyatin1

**Comment by MarkShidran** [comment]
Либа готова. Нужно написать скрипт для обновления (а не удаления) расписания в соответствии с изменениями

**Comment by MarkShidran** [comment]
Чеклист переехал в описание задачи

**Comment by MarkShidran** [comment]
@grigoriev-semyon, как тут дела?

**Comment by MarkShidran** [comment]
~~Блокер~~ Связана с https://github.com/profcomff/.github/issues/10

**Comment by dyakovri** [comment]
Не блокер. Когда Стас доберется, переделает просто под новые технологии. Но на текущих тоже можно сделать
