### ISSUE TITLE
Настроить обновление а не удаление ивентов

### ISSUE THREAD

**Issue by grigoriev-semyon** [profcomff/preparation-timetable-data#37]
Сейчас ивенты при изменениях расписания просто удаляются и затем загружаются полностью
При этом у них будут пропадать комменты

Надо сделать так, чтобы пары именно обновлялись через метод PATCH апишки

**Comment by MarkShidran** [comment]
Надо протестить это на реальных данных из HTMLек, который у нас есть

**Comment by MarkShidran** [comment]
#46

**Comment by MarkShidran** [comment]
На переписывании
